export const GET_ALL_NEWS = 'GET_ALL_NEWS'; 
export const GET_SINGLE_NEWS = 'GET_SINGLE_NEWS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const LANGUAGE = 'LANGUAGE';